<a href="https://colab.research.google.com/github/Mugundan-Senthilkumar/Technocolabs-Mini-proj/blob/main/Spotify_Music_Skips_Action_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spotify Music Skips Action Prediction

### Author: Mugundan Senthilkumar 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### Data preperation


In [2]:
from google.colab import files
uploaded=files.upload()

Saving technocolabs training set.csv to technocolabs training set.csv


In [ ]:
import io
data = pd.read_csv(io.BytesIO(uploaded['technocolabs training set.csv']))
data.head()

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218586 entries, 0 to 218585
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype  
---  ------                           --------------   -----  
 0   session_id                       167881 non-null  object 
 1   session_position                 167880 non-null  float64
 2   session_length                   167880 non-null  float64
 3   track_id_clean                   167880 non-null  object 
 4   skip_1                           167880 non-null  object 
 5   skip_2                           167880 non-null  object 
 6   skip_3                           167880 non-null  object 
 7   not_skipped                      167880 non-null  object 
 8   context_switch                   167880 non-null  float64
 9   no_pause_before_play             167880 non-null  float64
 10  short_pause_before_play          167880 non-null  float64
 11  long_pause_before_play           167880 non-null  float64
 12  hi

In [5]:
data.isnull().sum()

session_id                         50705
session_position                   50706
session_length                     50706
track_id_clean                     50706
skip_1                             50706
skip_2                             50706
skip_3                             50706
not_skipped                        50706
context_switch                     50706
no_pause_before_play               50706
short_pause_before_play            50706
long_pause_before_play             50706
hist_user_behavior_n_seekfwd       50706
hist_user_behavior_n_seekback      50706
hist_user_behavior_is_shuffle      50706
hour_of_day                        50706
date                               50706
premium                            50706
context_type                       50706
hist_user_behavior_reason_start    50706
hist_user_behavior_reason_end      50706
dtype: int64

In [6]:
data.drop_duplicates()


session_id  ...  hist_user_behavior_reason_end
0                  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                      trackdone
1                  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                      trackdone
2                  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                      trackdone
3                  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                      trackdone
4                  0_00006f66-33e5-4de7-a324-2d18e439fc1e  ...                      trackdone
...                                                   ...  ...                            ...
167877             0_0eaeef5d-25e9-4429-bd55-af15d3604c9f  ...                      trackdone
167878             0_0eaeef5d-25e9-4429-bd55-af15d3604c9f  ...                      trackdone
167879             0_0eaeef5d-25e9-4429-bd55-af15d3604c9f  ...                      trackdone
167880                                                NaN  ...                            NaN
218585                                                ...  ...                            NaN

[167882 rows x 21 columns]

In [7]:
data.shape

(218586, 21)

In [8]:
data.not_skipped.value_counts()

False    111996
True      55884
Name: not_skipped, dtype: int64

In [9]:
data.describe()

session_position  ...    hour_of_day
count     167880.000000  ...  167880.000000
mean           9.325911  ...      14.193084
std            5.457638  ...       5.996243
min            1.000000  ...       0.000000
25%            5.000000  ...      11.000000
50%            9.000000  ...      15.000000
75%           14.000000  ...      19.000000
max           20.000000  ...      23.000000

[8 rows x 9 columns]

In [10]:
pd.isnull(data).sum() > 0
data.dropna(inplace=True)

### Preprocessing

In [11]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


In [12]:
input_variable=data[['session_position','session_length','context_switch','no_pause_before_play','short_pause_before_play','long_pause_before_play','hist_user_behavior_n_seekfwd','hist_user_behavior_n_seekback','hour_of_day']]
output_variable=data['not_skipped']

In [13]:
labelencoder_skip= LabelEncoder()
output_variable=labelencoder_skip.fit_transform(output_variable)

output_variable

array([1, 1, 1, ..., 1, 1, 1])

### Training the model

In [14]:
x_train,x_test,y_train,y_test= train_test_split(input_variable, output_variable, test_size=0.2, random_state=1)

In [ ]:

logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

### Accuracy prediction

In [17]:
predictions = logmodel.predict(x_test)
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [19]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score

In [20]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.68      0.98      0.80     22530
           1       0.53      0.04      0.07     11046

    accuracy                           0.67     33576
   macro avg       0.60      0.51      0.43     33576
weighted avg       0.63      0.67      0.56     33576



In [21]:
accuracy_score(y_test,predictions)*100

67.22063378603764

In [22]:
confusion_matrix(predictions,y_test)

array([[22175, 10651],
       [  355,   395]])

### Model Presistance

In [23]:
import pickle

In [24]:
filename='spotify_prediction.sav'

In [25]:
pickle.dump(logmodel, open(filename, 'wb'))

In [26]:
load_model =pickle.load(open(filename, 'rb'))

In [27]:
predict=load_model.predict(x_test)

predict

array([0, 0, 0, ..., 0, 0, 0])